FROM node:10.1.0

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# add environment variables
ARG REACT_APP_USERS_SERVICE_URL
ARG REACT_APP_MOVIES_SERVICE_URL
ARG NODE_ENV
ARG REACT_APP_API_KEY
ENV REACT_APP_USERS_SERVICE_URL=$REACT_APP_USERS_SERVICE_URL
ENV REACT_APP_MOVIES_SERVICE_URL=$REACT_APP_MOVIES_SERVICE_URL
ENV NODE_ENV=$NODE_ENV
ENV REACT_APP_API_KEY=$REACT_APP_API_KEY


# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
ADD package.json /usr/src/app/package.json
RUN npm install --silent
RUN npm install -g serve --silent

# add app
ADD . /usr/src/app

# build react app
RUN npm run build

# start app
CMD ["serve", "-s", "build"]
