FROM node:10.1.0

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# Copy files and replace Windows line endings with UNIX ones
RUN apt-get update && apt-get install -y dos2unix
COPY . .
RUN find . -type f -print0 | xargs -0 dos2unix && apt-get --purge remove -y dos2unix && rm -rf /var/lib/apt/lists/*

# Install dependencies
RUN npm install --silent
RUN npm install -g serve --silent

# Build app and start server from script
CMD ["/usr/src/app/run"]