FROM node:10.1.0

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src

# add `/usr/src/node_modules/.bin` to $PATH
ENV PATH /usr/src/node_modules/.bin:$PATH

# install and cache app dependencies
ADD package.json /usr/src/package.json
RUN npm install

ADD ./entrypoint.sh /usr/src/entrypoint.sh

# add app
ADD . /usr/src/app

# Copy files and replace Windows line endings with UNIX ones
RUN apt-get update && apt-get install -y dos2unix
RUN find . -type f -print0 | xargs -0 dos2unix && apt-get --purge remove -y dos2unix && rm -rf /var/lib/apt/lists/*

# start app
RUN chmod +x ./entrypoint.sh
CMD ["./entrypoint.sh"]
